# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Update Version App

on:
  #push:
  #  paths:
  #    - 'app-release.apk'
  push:
    branches: [ "main" ]

  
env:
  ## Sets environment variable
  DIRECTORY_TO_DELETE: deleter 
  BRANCH: main
  MESSAGE: Testing
  NAME : DexterPlayer
  EMAIL : dexter.player.apps@github.com
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
         
    - name: Run script file
      run: |
         # cd apks
         # sudo apt install -y aapt 
         # aapt dump badging app-release.apk | grep "VersionName" | sed -e "s/.*versionName='//" -e "s/' .*//"

      
   # - name: Pushing to main branch
    #  uses: actions-js/push@master
     # with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
       #   branch: ${{ env.BRANCH }}
        #  message: ${{env.MESSAGE}}
         # author_name: ${{env.NAME}}
          #author_email: ${{env.EMAIL}}
          #force: true
